getwd()
setwd("C:/Users/Babul samal/Documents")
dir()
battery<-read.csv(file.choose())
View(battery)
attach(battery)
battery1<-battery[,4:9]
View(battery1)
dim(battery1)
sapply(battery1,class)
head(battery1)
summary(battery1)
range(SOC)
range(Grid.status)
xy <- as.data.frame(cbind(SOC,Grid.status))
xy <- scale(xy)
cor(SOC,Grid.status)#0.23,it shows a moderate positive correlation exists between them 
library(psych)
pairs.panels(xy)
library(ggplot2)
qqplot(SOC,Grid.status)
class(xy)
hist(battery1$SOC)
hist(battery1$Grid.status)
hist(battery1$SOH)
hist(battery1$Equivalent.cycle)
hist(battery1$Temperature)
pairs(xy)
table(Grid.status)
table(SOC)

yz <- as.data.frame(cbind(SOH,Equivalent.cycle))
yz<-scale(yz)
cor(SOH,Equivalent.cycle)#-0.98,so it shows strong negative correlation 
pairs.panels(yz)
pairs(yz)
table(SOH)
table(Equivalent.cycle)
table(Temperature)

wz <- as.data.frame(cbind(SOC,Temperature))
wz<-scale(wz)
cor(SOC,Temperature)#-0.37,so it shows weak negative correlation 
pairs.panels(wz)
pairs(wz)
